import { DataTypes } from "sequelize";
import { Pipeline } from "./pipeline";

export class CentrelinePipeline extends Pipeline {
  // { "type": "Feature", "properties": { "_id": 1, "CENTRELINE_ID": 914600, "LINEAR_NAME_ID": 2141, "LINEAR_NAME_FULL": "Morrison St", "LINEAR_NAME_FULL_LEGAL": "Morrison Street", "ADDRESS_L": "None", "ADDRESS_R": "None", "PARITY_L": "N", "PARITY_R": "N", "LO_NUM_L": 0, "HI_NUM_L": 0, "LO_NUM_R": 0, "HI_NUM_R": 0, "BEGIN_ADDR_POINT_ID_L": 0, "END_ADDR_POINT_ID_L": 0, "BEGIN_ADDR_POINT_ID_R": 0, "END_ADDR_POINT_ID_R": 0, "BEGIN_ADDR_L": 0, "END_ADDR_L": 0, "BEGIN_ADDR_R": 0, "END_ADDR_R": 0, "LOW_NUM_ODD": 0, "HIGH_NUM_ODD": 0, "LOW_NUM_EVEN": 0, "HIGH_NUM_EVEN": 0, "LINEAR_NAME": "Morrison", "LINEAR_NAME_TYPE": "St", "LINEAR_NAME_DIR": "None", "LINEAR_NAME_DESC": "ET", "LINEAR_NAME_LABEL": "Morrison St", "FROM_INTERSECTION_ID": 13470555, "TO_INTERSECTION_ID": 13470560, "ONEWAY_DIR_CODE": 0, "ONEWAY_DIR_CODE_DESC": "Not One-Way", "FEATURE_CODE": 201500, "FEATURE_CODE_DESC": "Local", "JURISDICTION": "CITY OF TORONTO", "CENTRELINE_STATUS": "None", "OBJECTID": 1, "MI_PRINX": 1 }, "geometry": { "type": "MultiLineString", "coordinates": [ [ [ -79.508749502141896, 43.597441242633003 ], [ -79.509871630129695, 43.597202099867701 ] ] ] } },
  constructor() {
    super(
      "https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/1d079757-377b-4564-82df-eb5638583bfb/resource/7bc94ccf-7bcf-4a7d-88b1-bdfc8ec5aaf1/download/centreline-version-2-4326.geojson",
      "centreline",
      {
        id: {
          type: DataTypes.STRING,
          primaryKey: true,
        },
        centreline_id: DataTypes.INTEGER,
        linear_name_id: DataTypes.INTEGER,
        full_name: DataTypes.STRING,
        legal_name: DataTypes.STRING,
        address_l: DataTypes.STRING,
        address_r: DataTypes.STRING,
        parity_l: DataTypes.STRING,
        parity_r: DataTypes.STRING,
        lo_num_l: DataTypes.INTEGER,
        hi_num_l: DataTypes.INTEGER,
        lo_num_r: DataTypes.INTEGER,
        hi_num_r: DataTypes.INTEGER,
        begin_addr_point_id_l: DataTypes.INTEGER,
        end_addr_point_id_l: DataTypes.INTEGER,
        begin_addr_point_id_r: DataTypes.INTEGER,
        end_addr_point_id_r: DataTypes.INTEGER,
        begin_addr_l: DataTypes.INTEGER,
        end_addr_l: DataTypes.INTEGER,
        begin_addr_r: DataTypes.INTEGER,
        end_addr_r: DataTypes.INTEGER,
        low_num_odd: DataTypes.INTEGER,
        high_num_odd: DataTypes.INTEGER,
        low_num_even: DataTypes.INTEGER,
        high_num_even: DataTypes.INTEGER,
        linear_name: DataTypes.STRING,
        linear_name_type: DataTypes.STRING,
        linear_name_dir: DataTypes.STRING,
        description: DataTypes.STRING,
        label: DataTypes.STRING,
        from_intersection_id: DataTypes.INTEGER,
        to_intersection_id: DataTypes.INTEGER,
        oneway_dir_code: DataTypes.INTEGER,
        oneway_dir_desc: DataTypes.STRING,
        fcode: DataTypes.INTEGER,
        fcode_description: DataTypes.STRING,
        geometry: DataTypes.GEOMETRY,
      },
      {
        _id: "id",
        CENTRELINE_ID: "centreline_id",
        LINEAR_NAME_ID: "linear_name_id",
        LINEAR_NAME_FULL: "full_name",
        LINEAR_NAME_FULL_LEGAL: "legal_name",
        ADDRESS_L: "address_l",
        ADDRESS_R: "address_r",
        PARITY_L: "parity_l",
        PARITY_R: "parity_r",
        LO_NUM_L: "lo_num_l",
        HI_NUM_L: "hi_num_l",
        LO_NUM_R: "lo_num_r",
        HI_NUM_R: "hi_num_r",
        BEGIN_ADDR_POINT_ID_L: "begin_addr_point_id_l",
        END_ADDR_POINT_ID_L: "end_addr_point_id_l",
        BEGIN_ADDR_POINT_ID_R: "begin_addr_point_id_r",
        END_ADDR_POINT_ID_R: "end_addr_point_id_r",
        BEGIN_ADDR_L: "begin_addr_l",
        END_ADDR_L: "end_addr_l",
        BEGIN_ADDR_R: "begin_addr_r",
        END_ADDR_R: "end_addr_r",
        LOW_NUM_ODD: "low_num_odd",
        HIGH_NUM_ODD: "high_num_odd",
        LOW_NUM_EVEN: "low_num_even",
        HIGH_NUM_EVEN: "high_num_even",
        LINEAR_NAME: "linear_name",
        LINEAR_NAME_TYPE: "linear_name_type",
        LINEAR_NAME_DIR: "linear_name_dir",
        LINEAR_NAME_DESC: "description",
        LINEAR_NAME_LABEL: "label",
        FROM_INTERSECTION_ID: "from_intersection_id",
        TO_INTERSECTION_ID: "to_intersection_id",
        ONEWAY_DIR_CODE: "oneway_dir_code",
        ONEWAY_DIR_CODE_DESC: "oneway_dir_desc",
        FEATURE_CODE: "fcode",
        FEATURE_CODE_DESC: "fcode_description",
      }
    );
  }
}
